In [1]:
import torch

In [2]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [3]:
features=torch.randn((1,3))
features

tensor([[ 0.7038, -0.7482,  0.2832]])

In [5]:
n_input=features.shape[1]
n_input

3

In [6]:
n_hidden=2
n_output=1

In [7]:
w1=torch.randn(n_input,n_hidden)
w1

tensor([[-0.2735,  0.0551],
        [-0.5957, -0.7525],
        [ 1.8753, -1.3744]])

In [8]:
w2=torch.randn(n_hidden,n_output)
w2

tensor([[1.2486],
        [1.2879]])

In [18]:
bias1=torch.randn((1,1))
bias1
bias2=torch.randn((1,1))
bias2

tensor([[0.1380]])

In [17]:
hidden=torch.mm(features,w1)+bias1
hidden

tensor([[-0.3207, -0.8925]])

In [19]:
output=torch.mm(hidden,w2)+bias2

In [20]:
output

tensor([[-1.4119]])

In [21]:
output=activation(output)
output

tensor([[0.1959]])